.\"
.\"	wrapc -- comment reformatter
.\"	wrapc.1: manual page
.\"
.\"	Copyright (C) 1996-2005  Paul J. Lucas
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the Licence, or
.\"	(at your option) any later version.
.\" 
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\" 
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH \f3wrapc\f1 1 "July 3, 2005" "PJL TOOLS"
.SH NAME
wrapc \- comment reformatter
.SH SYNOPSIS
.B wrapc
[
.B \-l
.I line-length
] [
.B \-v
]
.SH DESCRIPTION
.B wrapc
is a filter for reformatting program comments by
wrapping and filling lines to a given
.IR line-length ,
the default for which is 80 characters.
This can be changed via the
.B \-l
option.
.P
Leading white-space and comment delimiters are preserved.
The characters that are recognized as comment delimeters are:
.IP "\f3!\f1" 10
HTML and XML comments.
.IP "\f3#\f1" 10
Shell, Make, and Perl comments.
.IP "\f3/\f1 and \f3*\f1" 10
C, C++, and Java comments.
.IP "\f3%\f1" 10
PostScript comments.
.IP "\f3;\f1" 10
Assember and Lisp comments.
.IP "\f3>\f1" 10
Forwarded mail indicator.
.P
All other white-space characters are folded
in the same manner as in
.BR wrap .
.SH OPTIONS
.IP "\f3\-l\f2 n\f1"
Set
.I line-length
to
.I n
characters.
.IP "\f3\-v\f1"
Print the version number to
.I stderr
and exit.
.SH EXAMPLE
While in
.IR vi ,
wrap the comment covering the current and subsequent 3 lines.
.IP ""
!\f33\f2return\f1wrapc\f1
.SH SEE ALSO
.BR vi (1),
.BR wrap (1)
.SH AUTHOR
Paul J. Lucas
.RI < pjl@best.com >
