.\"
.\"	wrapc -- comment reformatter
.\"	wrapc.1: manual page
.\"
.\"	Copyright (C) 1996-2015  Paul J. Lucas
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the Licence, or
.\"	(at your option) any later version.
.\" 
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\" 
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" ---------------------------------------------------------------------------
.\" define code-start macro
.de cS
.sp
.nf
.RS 5
.ft CW
.ta .5i 1i 1.5i 2i 2.5i 3i 3.5i 4i 4.5i 5i 5.5i
..
.\" define code-end macro
.de cE
.ft 1
.RE
.fi
.if !'\\$1'0' .sp
..
.\" ---------------------------------------------------------------------------
.TH \f3wrapc\f1 1 "March 10, 2016" "PJL TOOLS"
.SH NAME
wrapc \- comment reformatter
.SH SYNOPSIS
.B wrapc
.BI [ options ]
.SH DESCRIPTION
.B wrapc
is a filter for reformatting source code comments
(or quoted e-mail)
by wrapping and filling lines to a given
.IR line-width ,
the default for which is 80 characters.
.P
The characters that are recognized as comment delimeters are:
.P
.PD 0
.IP "\f(CW!\f1" 10
HTML and XML comments.
.IP "\f(CW#\f1" 10
CMake, Make, Perl, Python, Ruby, and Shell comments.
.IP "\f(CW/\f1 and \f(CW*\f1" 10
C, C++, and Java comments.
.IP "\f(CW%\f1" 10
PostScript comments.
.IP "\f(CW:\f1" 10
XQuery comments.
.IP "\f(CW;\f1" 10
Assember and Lisp comments.
.IP "\f(CW>\f1" 10
Quoted mail indicator.
.PD
.P
Leading whitespace and comment delimiters
of the first line
are used as the prototype for all lines.
For each line,
all leading whitespace and comment delimiters are stripped
before being passed to
.BR wrap (1)
for reformatting.
After reformatting,
the prototype characters
of the first comment line
are prepended at the start of each line.
All other whitespace characters are folded
in the same manner as in
.BR wrap .
.P
If a subsequent line does not start with whitespace
followed by comment delimiters,
it signals the end of the comment
and all remaining lines
are passed through verbatim.
However,
if the first line starts with whitespace
but is
.I not
followed by comment delimiters,
then the whitespace alone is used as the prototype for all lines.
.SH OPTIONS
An option argument
.I f
means
.IR file ,
.I n
means
.IR "unsigned integer" ,
and
.I s
means
.IR string .
.TP
.BI \-a " s"
Specifies the alias name
.I s
from the configuration file to be used.
This overrides any alias
from a matched pattern
via either the
.B \-f
or
.B \-F
options.
.TP
.BI \-c " f"
Specifies the configuration file
.I f
to read
(default is
.BR ~/.wraprc )
if warranted.
.TP
.B \-C
Suppresses reading of any configuration file,
even one explicitly specified via
.BR \-c .
.TP
.B \-e
Treats white-space after an end-of-sentence character as a paragraph delimiter.
.TP
.BI \-f " f"
Reads from file
.I f
(default is standard input).
.TP
.BI \-F " f"
Sets the file-name to
.I f
as if it were being read from
but still reads from standard input.
(This allows the file-name to be matched against a pattern
in a configuration file to use an alias
while still allowing
.B wrapc
to be used as part of a shell pipeline.)
.TP
.BI \-l " n"
Deprecated.
Now a synonym for
.BR \-w .
.TP
.BI \-o " f"
Writes to file
.I f
(default is standard output).
.TP
.BI \-p " s"
Treats the given characters in
.I s
as paragraph delimiters.
.TP
.BI \-s " n"
Sets
.I tab-spaces
(the number of spaces a tab character should be considered the same as)
to
.I n
characters
(default is 8).
.TP
.B \-T
Treats the first line of every paragraph as a title
and puts it on a line by itself.
.TP
.B \-v
Prints the version number to
.I stderr
and exits.
.TP
.BI \-w " n"
Sets
.I line-width
to
.I n
characters
(default is 80).
.SH EXIT STATUS
.PD 0
.IP 0
Success.
.IP 64
Command-line usage error.
.IP 66
Open file error.
.IP 71
System error.
.IP 73
Create file error.
.IP 74
I/O error.
.IP 78
Error in configuration file.
.PD
.SH ENVIRONMENT
.TP
.B HOME
The user's home directory:
used to locate the default configuration file.
If unset,
the home directory is obtained from the password database entry
for the effective user.
If that fails,
no default configuration file is read.
.SH FILES
.TP
.B ~/.wraprc
The default configuration file.
A configuration file,
even one explicitly specified via
.BR \-c ,
is neither actually checked for existence nor read
unless one of the
.BR \-a ,
.BR \-f ,
or
.B \-F
options
is specified
since it doesn't affect the result.
.SH EXAMPLE
While in
.BR vi ,
wrap the comment from the current line to the end of the paragraph:
.cS
!}wrapc -F'%'
.cE
The \f(CW%\f1 argument to the
.B \-F
option is expaned by
.B vi
to be the file's path name.
To lessen typing,
the above can be mapped to a key sequence in
.BR vi 's
\f(CW.exrc\f1
file:
.cS
map `c !}wrap -F'%'\f3^M\f1
.cE 0
.SH AUTHOR
Paul J. Lucas
.RI < paul@lucasmail.org >
.SH SEE ALSO
.BR vi (1),
.BR wrap (1),
.BR wraprc (5)
